CREATE TABLE IF NOT EXISTS `admin_assinaturas_licencas` (
  `id` int AUTO_INCREMENT NOT NULL PRIMARY KEY,
  `serviceName` varchar(255) NOT NULL,
  `category` enum('Segurança', 'IA/LLM', 'Infraestrutura', 'Software', 'Outro') NOT NULL,
  `renewalType` enum('Mensal', 'Anual', 'Personalizado') NOT NULL,
  `renewalDays` int,
  `startDate` bigint NOT NULL,
  `expirationDate` bigint NOT NULL,
  `value` decimal(12, 2) NOT NULL,
  `currency` enum('BRL', 'USD') NOT NULL DEFAULT 'BRL',
  `status` enum('Ativo', 'Próximo do vencimento', 'Vencido', 'Cancelado') NOT NULL DEFAULT 'Ativo',
  `notes` text,
  `responsibleUserId` int NOT NULL,
  `responsibleUserName` varchar(255) NOT NULL,
  `alertDaysBefore` int NOT NULL DEFAULT 30,
  `alertEnabled` boolean NOT NULL DEFAULT true,
  `groupId` int NOT NULL,
  `createdById` int NOT NULL,
  `createdByName` varchar(255) NOT NULL,
  `createdAt` bigint NOT NULL,
  `updatedAt` bigint NOT NULL,
  INDEX `sub_service_idx` (`serviceName`),
  INDEX `sub_category_idx` (`category`),
  INDEX `sub_status_idx` (`status`),
  INDEX `sub_expiration_idx` (`expirationDate`),
  INDEX `sub_responsible_idx` (`responsibleUserId`),
  INDEX `sub_group_idx` (`groupId`)
);
